#mekanism (bugged: removing one recipe clears all recipes for these machines)
#-------

#crusher
mods.mekanism.Crusher.removeRecipe(<TConstruct:materials:16>);
mods.mekanism.Crusher.removeRecipe(<Mekanism:Ingot:4>);

mods.mekanism.Crusher.addRecipe(<minecraft:stonebrick:3>, <minecraft:stonebrick:0>);
mods.mekanism.Crusher.addRecipe(<minecraft:stonebrick:0>, <minecraft:stonebrick:2>);
mods.mekanism.Crusher.addRecipe(<minecraft:stone>, <minecraft:cobblestone>);
mods.mekanism.Crusher.addRecipe(<minecraft:cobblestone>, <minecraft:sand>);
mods.mekanism.Crusher.addRecipe(<minecraft:gravel>, <minecraft:sand>);
mods.mekanism.Crusher.addRecipe(<minecraft:sandstone:0>, <minecraft:sand>*2);
mods.mekanism.Crusher.addRecipe(<minecraft:sandstone:1>, <minecraft:sand>*2);
mods.mekanism.Crusher.addRecipe(<minecraft:sandstone:2>, <minecraft:sand>*2);

mods.mekanism.Crusher.addRecipe(<minecraft:diamond>*1, <Mekanism:Dust:4> * 1);
mods.mekanism.Crusher.addRecipe(<AncientWarfare:steel_ingot>, <Mekanism:Dust:5> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Ingot:1>, <Mekanism:Dust:2> * 1);
mods.mekanism.Crusher.addRecipe(<appliedenergistics2:item.ItemMultiMaterial:7>, <appliedenergistics2:item.ItemMultiMaterial:8> * 1);
mods.mekanism.Crusher.addRecipe(<appliedenergistics2:item.ItemMultiMaterial:0>, <appliedenergistics2:item.ItemMultiMaterial:2> * 1);
mods.mekanism.Crusher.addRecipe(<appliedenergistics2:item.ItemMultiMaterial:1>, <appliedenergistics2:item.ItemMultiMaterial:2> * 1);
mods.mekanism.Crusher.addRecipe(<minecraft:ender_pearl>, <appliedenergistics2:item.ItemMultiMaterial:46> * 1);
mods.mekanism.Crusher.addRecipe(<minecraft:flint>, <minecraft:gunpowder>);
mods.mekanism.Crusher.addRecipe(<minecraft:quartz>, <appliedenergistics2:item.ItemMultiMaterial:2>);
mods.mekanism.Crusher.addRecipe(<appliedenergistics2:tile.BlockSkyStone:0>, <appliedenergistics2:item.ItemMultiMaterial:45> * 1);
mods.mekanism.Crusher.addRecipe(<minecraft:coal:1>, <ThermalFoundation:material:3> * 1);

mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:0>, <Mekanism:DirtyDust:0> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:1>, <Mekanism:DirtyDust:1> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:2>, <Mekanism:DirtyDust:2> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:3>, <Mekanism:DirtyDust:3> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:4>, <Mekanism:DirtyDust:4> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:5>, <Mekanism:DirtyDust:5> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:6>, <Mekanism:DirtyDust:6> * 1);
mods.mekanism.Crusher.addRecipe(<Mekanism:Clump:7>, <Mekanism:DirtyDust:7> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpNickel>, <aobd:dustDirtyNickel> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpPlatinum>, <aobd:dustDirtyPlatinum> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpMithril>, <aobd:dustDirtyMithril> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpYellorium>, <aobd:dustDirtyUranium> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpAluminium>, <aobd:dustDirtyAluminium> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpRutile>, <aobd:dustDirtyRutile> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpUranium>, <aobd:dustDirtyUranium> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpCobalt>, <aobd:dustDirtyCobalt> * 1);
mods.mekanism.Crusher.addRecipe(<aobd:clumpArdite>, <aobd:dustDirtyArdite> * 1);
mods.mekanism.Crusher.addRecipe(<CustomItems:clumpTitanium>, <CustomItems:dustTitaniumDirty> * 1);
mods.mekanism.Crusher.addRecipe(<CustomItems:clumpDesh>, <CustomItems:dustDeshDirty> * 1);

mods.mekanism.Crusher.addRecipe(<minecraft:sapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Natura:florasapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Natura:Rare Sapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Natura:Rare Sapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<BiomesOPlenty:saplings:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<BiomesOPlenty:colorizedSaplings:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Forestry:sapling:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<psychedelicraft:psycheSapling:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<witchery:witchsapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingBaobab:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingEucalyptus:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingMahogany:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingMossbark:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingAsper:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingCypress:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<erebus:saplingSap:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<TwilightForest:tile.TFSapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<MorePlanet:nibiru_sapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<MorePlanet:fronos_sapling:32767>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<minecraft:pumpkin_seeds:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<minecraft:melon_seeds:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:asparagusseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:barleyseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:beanseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:beetseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:broccoliseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cauliflowerseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:celeryseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cranberryseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:garlicseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:gingerseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:leekseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:lettuceseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:oatsseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:onionseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:parsnipseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:peanutseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:pineappleseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:radishseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:ryeseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:scallionseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:soybeanseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:spiceleafseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:sunflowerseedsItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:sweetpotatoseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:teaseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:turnipseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:whitemushroomseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:bellpepperseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:blackberryseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:blueberryseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cactusfruitseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cantaloupeseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:chilipepperseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:coffeeseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cornseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cucumberseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:eggplantseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:grapeseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:kiwiseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:mustardseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:peasseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:raspberryseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:rhubarbseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:seaweedseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:strawberryseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:tomatoseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:wintersquashseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:zucchiniseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:bambooshootseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:spinachseedItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedPotato:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedCarrot:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedSugarcane:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedDandelion:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedPoppy:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedOrchid:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedAllium:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedTulipRed:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedTulipOrange:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedTulipWhite:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedTulipPink:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedDaisy:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedDiamahlia:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedFerranium:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedAurigold:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedLapender:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedCuprosia:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedPetinia:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedPlombean:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedSilverweed:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedJaslumine:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedNiccissus:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<AgriCraft:seedPlatiolus:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Natura:barleyFood:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<witchery:seedsbelladonna:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<witchery:seedsmandrake:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<witchery:seedsartichoke:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<witchery:seedssnowbell:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<witchery:seedswormwood:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Natura:barley.seed:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<Natura:barley.seed:1>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<BiomesOPlenty:food:3>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<BiomesOPlenty:turnipSeeds:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:gingerItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:spiceleafItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<harvestcraft:mustardseedsItem:0>,<Mekanism:BioFuel> * 2);
mods.mekanism.Crusher.addRecipe(<minecraft:apple:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cranberryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:pineappleItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:blackberryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:blueberryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cactusfruitItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cantaloupeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:grapeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:kiwiItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:raspberryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:strawberryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:bananaItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cherryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:dragonfruitItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:lemonItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:limeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:mangoItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:orangeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:papayaItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:peachItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:pearItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:plumItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:pomegranateItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:starfruitItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:apricotItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:dateItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:figItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:grapefruitItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:persimmonItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<minecraft:melon:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Forestry:fruits:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Forestry:fruits:3>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Forestry:fruits:4>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Forestry:fruits:5>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Forestry:fruits:6>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:NetherBerryBush:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:NetherBerryBush:1>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:NetherBerryBush:2>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:NetherBerryBush:3>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:berry:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:berry:1>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:berry:2>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:berry:3>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<minecraft:wheat:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:barleyItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:oatsItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:ryeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<Natura:barleyFood:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:asparagusItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:broccoliItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:celeryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:lettuceItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:spiceleafItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:artichokeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:brusselsproutItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cabbageItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cucumberItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:okraItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:peasItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:seaweedItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:zucchiniItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:spinachItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:garlicItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<minecraft:carrot:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<minecraft:potato:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<minecraft:pumpkin:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:asparagusItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:beanItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:beetItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:broccoliItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cauliflowerItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:celeryItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:leekItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:lettuceItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:onionItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:parsnipItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:radishItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:rutabagaItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:scallionItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:soybeanItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:sweetpotatoItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:turnipItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:whitemushroomItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:artichokeItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:bellpepperItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:brusselsproutItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cabbageItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cornItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:cucumberItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:eggplantItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:okraItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:peasItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:rhubarbItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:seaweedItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:tomatoItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:wintersquashItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:zucchiniItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:bambooshootItem:0>,<Mekanism:BioFuel> * 4);
mods.mekanism.Crusher.addRecipe(<harvestcraft:spinachItem:0>,<Mekanism:BioFuel> * 4);

mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:64>, <ThermalFoundation:material:32>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:65>, <ThermalFoundation:material:33>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:66>, <ThermalFoundation:material:34>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:67>, <ThermalFoundation:material:35>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:68>, <ThermalFoundation:material:36>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:69>, <ThermalFoundation:material:37>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:70>, <ThermalFoundation:material:38>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:71>, <ThermalFoundation:material:39>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:72>, <ThermalFoundation:material:40>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:73>, <ThermalFoundation:material:41>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:74>, <ThermalFoundation:material:42>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:75>, <ThermalFoundation:material:43>);
mods.mekanism.Crusher.addRecipe(<ThermalFoundation:material:76>, <ThermalFoundation:material:44>);
mods.mekanism.Crusher.addRecipe(<minecraft:iron_ingot>, <ThermalFoundation:material:0>);
mods.mekanism.Crusher.addRecipe(<minecraft:gold_ingot>, <ThermalFoundation:material:1>);
mods.mekanism.Crusher.addRecipe(<BigReactors:BRIngot:0>, <BigReactors:BRIngot:4>);
mods.mekanism.Crusher.addRecipe(<BigReactors:BRIngot:1>, <BigReactors:BRIngot:5>);
mods.mekanism.Crusher.addRecipe(<BigReactors:BRIngot:2>, <BigReactors:BRIngot:6>);
mods.mekanism.Crusher.addRecipe(<BigReactors:BRIngot:3>, <BigReactors:BRIngot:7>);
mods.mekanism.Crusher.addRecipe(<BigReactors:BRIngot:8>, <BigReactors:BRIngot:9>);
mods.mekanism.Crusher.addRecipe(<Mekanism:Ingot:0>, <Mekanism:Dust:3>);
mods.mekanism.Crusher.addRecipe(<Mekanism:Ingot:3>, <minecraft:glowstone_dust>);

mods.mekanism.Crusher.addRecipe(<minecraft:wool:0>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:1>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:2>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:3>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:4>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:5>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:6>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:7>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:8>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:9>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:10>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:11>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:12>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:13>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:14>*1,<minecraft:string>*4);
mods.mekanism.Crusher.addRecipe(<minecraft:wool:15>*1,<minecraft:string>*4);


#enrichment
mods.mekanism.Enrichment.removeRecipe(<Mekanism:Dust:1>*1);
mods.mekanism.Enrichment.removeRecipe(<Mekanism:Dust:6>*1);
mods.mekanism.Enrichment.removeRecipe(<Mekanism:Dust:6>*2);
mods.mekanism.Enrichment.removeRecipe(<Mekanism:Dust:7>*2);
mods.mekanism.Enrichment.removeRecipe(<Mekanism:Dust:8>*2);
mods.mekanism.Enrichment.removeRecipe(<Mekanism:Dust:8>*1);

mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:0>*1, <ThermalFoundation:material:0> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:1>*1, <ThermalFoundation:material:1> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:2>*1, <Mekanism:Dust:2> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:3>*1, <ThermalFoundation:material:32> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:4>*1, <ThermalFoundation:material:33> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:5>, <ThermalFoundation:material:34> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:6>, <Mekanism:Dust:3> * 1);
mods.mekanism.Enrichment.addRecipe(<Mekanism:DirtyDust:7>, <ThermalFoundation:material:35> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyNickel>*1, <ThermalFoundation:material:36> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyPlatinum>*1, <ThermalFoundation:material:37> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyMithril>*1, <ThermalFoundation:material:38> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyYellorium>*1, <ResonantInductionCore:yellowCake> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyAluminium>, <TConstruct:materials:40> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyRutile>, <aobd:dustRutile> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyUranium>, <ResonantInductionCore:yellowCake> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyCobalt>, <TConstruct:materials:39> * 1);
mods.mekanism.Enrichment.addRecipe(<aobd:dustDirtyArdite>, <TConstruct:materials:38> * 1);
mods.mekanism.Enrichment.addRecipe(<CustomItems:dustTitaniumDirty>, <CustomItems:dustTitanium> * 1);
mods.mekanism.Enrichment.addRecipe(<CustomItems:dustDeshDirty>, <CustomItems:dustDesh> * 1);

mods.mekanism.Enrichment.addRecipe(<minecraft:iron_ore>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<minecraft:gold_ore>, <ThermalFoundation:material:1>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:0>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:1>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:2>, <ThermalFoundation:material:34>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:3>, <ThermalFoundation:material:35>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:4>, <ThermalFoundation:material:36>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:5>, <ThermalFoundation:material:37>*2);
mods.mekanism.Enrichment.addRecipe(<ThermalFoundation:Ore:6>, <ThermalFoundation:material:38>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:SearedBrick:5>, <TConstruct:materials:40>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:SearedBrick:1>, <TConstruct:materials:39>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:SearedBrick:2>, <TConstruct:materials:38>*2);
mods.mekanism.Enrichment.addRecipe(<Mekanism:OreBlock:0>, <Mekanism:Dust:2>*2);
mods.mekanism.Enrichment.addRecipe(<minechem:tile.oreUranium>, <ResonantInductionCore:yellowCake>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:GravelOre:0>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:GravelOre:1>, <ThermalFoundation:material:1>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:GravelOre:2>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:GravelOre:3>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:GravelOre:4>, <TConstruct:materials:40>*2);
mods.mekanism.Enrichment.addRecipe(<TConstruct:GravelOre:5>, <TConstruct:materials:39>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftCore:tile.moonBlock:0>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftMars:tile.mars:0>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:diona_block:7>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:polongnius_block:4>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:koentus_block:5>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:fronos_block:6>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:kapteyn-b_block:8>, <ThermalFoundation:material:32>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftCore:tile.moonBlock:1>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftMars:tile.mars:1>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:diona_block:6>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:polongnius_block:5>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:koentus_block:4>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:fronos_block:5>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:kapteyn-b_block:7>, <ThermalFoundation:material:33>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftMars:tile.asteroidsBlock:15>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftMars:tile.mars:3>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:polongnius_block:6>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:fronos_block:2>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<erebus:oreIron>, <ThermalFoundation:material:0>*2);
mods.mekanism.Enrichment.addRecipe(<erebus:oreGold>, <ThermalFoundation:material:1>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:diona_block:9>, <TConstruct:materials:40>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:fronos_block:4>, <TConstruct:materials:40>*2);
mods.mekanism.Enrichment.addRecipe(<MorePlanet:kapteyn-b_block:6>, <ResonantInductionCore:yellowCake>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftMars:tile.mars:2>, <CustomItems:dustDesh>*2);
mods.mekanism.Enrichment.addRecipe(<GalacticraftMars:tile.asteroidsBlock:4>, <CustomItems:dustTitanium>*2);

mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseIron>, <ThermalFoundation:material:0>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseGold>, <ThermalFoundation:material:1>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseCopper>, <ThermalFoundation:material:32>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseTin>, <ThermalFoundation:material:33>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseSilver>, <ThermalFoundation:material:34>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseLead>, <ThermalFoundation:material:35>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseNickel>, <ThermalFoundation:material:36>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDensePlatinum>, <ThermalFoundation:material:37>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseAluminum>, <TConstruct:materials:40>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseOsmium>, <Mekanism:Dust:2>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseUranium>, <ResonantInductionCore:yellowCake>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseArdite>, <TConstruct:materials:38>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseCobalt>, <TConstruct:materials:39>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:oreDenseQuartz>, <minecraft:quartz>*12);

val denseLapis = <CustomItems:oreDenseLapis:0>;
val denseDiamond = <CustomItems:oreDenseDiamond:0>;
val denseEmerald = <CustomItems:oreDenseEmerald:0>;
val denseRedstone = <CustomItems:oreDenseRedstone:0>;
val denseCoal = <CustomItems:oreDenseCoal:0>;
val denseNetherQuartz = <CustomItems:oreDenseQuartz:0>;
val denseApatite = <CustomItems:oreDenseApatite:0>;
val denseQuantum = <CustomItems:oreDenseQuantum:0>;
val denseSulfur = <CustomItems:oreDenseSulfur:0>;
val denseSilicon = <CustomItems:oreDenseSilicon:0>;
val denseCertusQuartz = <CustomItems:oreDenseCertus:0>;

mods.mekanism.Enrichment.addRecipe(denseLapis*1, <minecraft:dye:4>*18);
mods.mekanism.Enrichment.addRecipe(denseCoal*1, <minecraft:coal:0>*4);
mods.mekanism.Enrichment.addRecipe(denseRedstone*12, <minecraft:redstone>*24);
mods.mekanism.Enrichment.addRecipe(denseDiamond*1, <minecraft:diamond>*4);
mods.mekanism.Enrichment.addRecipe(denseEmerald*1, <minecraft:emerald>*4);
mods.mekanism.Enrichment.addRecipe(denseNetherQuartz*1, <minecraft:quartz>*12);
mods.mekanism.Enrichment.addRecipe(denseApatite*1, <Forestry:apatite>*18);
mods.mekanism.Enrichment.addRecipe(denseSulfur*1, <Railcraft:dust:1>*12);
mods.mekanism.Enrichment.addRecipe(denseQuantum*1, <qCraft:dust>*8);
mods.mekanism.Enrichment.addRecipe(denseSilicon*1, <GalacticraftCore:item.basicItem:2>*4);
mods.mekanism.Enrichment.addRecipe(denseCertusQuartz*1, <appliedenergistics2:item.ItemMultiMaterial:2>*4);

mods.mekanism.Enrichment.addRecipe(<Railcraft:ore:7>, <ThermalFoundation:material:8>*4);
mods.mekanism.Enrichment.addRecipe(<Railcraft:ore:8>, <minecraft:gold_nugget>*4);
mods.mekanism.Enrichment.addRecipe(<Railcraft:ore:9>, <ThermalFoundation:material:96>*4);
mods.mekanism.Enrichment.addRecipe(<Railcraft:ore:10>, <ThermalFoundation:material:97>*4);
mods.mekanism.Enrichment.addRecipe(<Railcraft:ore:11>, <ThermalFoundation:material:99>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:orePoorAluminum>, <TConstruct:materials:22>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:orePoorOsmium>, <CustomItems:nuggetOsmium>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:orePoorPlatinum>, <ThermalFoundation:material:101>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:orePoorSilver>, <ThermalFoundation:material:98>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:orePoorNickel>, <ThermalFoundation:material:100>*4);
mods.mekanism.Enrichment.addRecipe(<CustomItems:orePoorUranium>, <CustomItems:nuggetUranium>*4);

mods.mekanism.Enrichment.addRecipe(<minecraft:diamond_ore>, <minecraft:diamond>*2);
mods.mekanism.Enrichment.addRecipe(<minecraft:coal_ore>, <minecraft:coal:0>*2);
mods.mekanism.Enrichment.addRecipe(<minecraft:redstone_ore>, <minecraft:redstone>*8);
mods.mekanism.Enrichment.addRecipe(<minecraft:quartz_ore>, <minecraft:quartz>*6);
mods.mekanism.Enrichment.addRecipe(<minecraft:lapis_ore>, <minecraft:dye:4>*8);
mods.mekanism.Enrichment.addRecipe(<appliedenergistics2:tile.OreQuartz>, <appliedenergistics2:item.ItemMultiMaterial:2>*2);
mods.mekanism.Enrichment.addRecipe(<appliedenergistics2:tile.OreQuartzCharged>, <appliedenergistics2:item.ItemMultiMaterial:2>*2);

mods.mekanism.Enrichment.addRecipe(<minecraft:gravel>, <minecraft:cobblestone>);
mods.mekanism.Enrichment.addRecipe(<minecraft:glowstone>, <minecraft:glowstone_dust>*4);
mods.mekanism.Enrichment.addRecipe(<minecraft:clay>, <minecraft:clay_ball>*4);

mods.mekanism.Enrichment.addRecipe(<minecraft:coal:0>, <Mekanism:CompressedCarbon>);
mods.mekanism.Enrichment.addRecipe(<minecraft:coal:1>, <Mekanism:CompressedCarbon>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:Dust:3>, <Mekanism:CompressedObsidian>);
mods.mekanism.Enrichment.addRecipe(<minecraft:stonebrick:0>, <minecraft:stonebrick:3>);
mods.mekanism.Enrichment.addRecipe(<minecraft:redstone>, <Mekanism:CompressedRedstone>);
mods.mekanism.Enrichment.addRecipe(<minecraft:diamond>, <Mekanism:CompressedDiamond>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:SaltBlock>, <Mekanism:Salt>*4);
mods.mekanism.Enrichment.addRecipe(<minecraft:obsidian>, <Mekanism:DirtyDust:6>*2);

mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:0>, <Mekanism:SlickPlasticBlock:0>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:1>, <Mekanism:SlickPlasticBlock:1>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:2>, <Mekanism:SlickPlasticBlock:2>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:3>, <Mekanism:SlickPlasticBlock:3>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:4>, <Mekanism:SlickPlasticBlock:4>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:5>, <Mekanism:SlickPlasticBlock:5>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:6>, <Mekanism:SlickPlasticBlock:6>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:7>, <Mekanism:SlickPlasticBlock:7>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:8>, <Mekanism:SlickPlasticBlock:8>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:9>, <Mekanism:SlickPlasticBlock:9>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:10>, <Mekanism:SlickPlasticBlock:10>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:11>, <Mekanism:SlickPlasticBlock:11>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:12>, <Mekanism:SlickPlasticBlock:12>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:13>, <Mekanism:SlickPlasticBlock:13>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:14>, <Mekanism:SlickPlasticBlock:14>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:15>, <Mekanism:SlickPlasticBlock:15>);
mods.mekanism.Enrichment.addRecipe(<Mekanism:PlasticBlock:16>, <Mekanism:SlickPlasticBlock:16>);
