val steel = <ore:ingotSteel>;
val gccompressor = <GalacticraftCore:tile.machine:12>;
val gccoalgen = <GalacticraftCore:tile.machine:0>;
val eleccompressor = <GalacticraftCore:tile.machine2:0>;
val circfab = <GalacticraftCore:tile.machine2:4>;
val gcrefinery = <GalacticraftCore:tile.refinery>;
val compcopper = <GalacticraftCore:item.basicItem:6>;
val comptin = <GalacticraftCore:item.basicItem:7>;
val compaluminum = <GalacticraftCore:item.basicItem:8>;
val compsteel = <GalacticraftCore:item.basicItem:9>;
val compbronze = <GalacticraftCore:item.basicItem:10>;
val compiron = <GalacticraftCore:item.basicItem:11>;
val compmeteoriron = <GalacticraftCore:item.meteoricIronIngot:1>;
val compdesh = <GalacticraftMars:item.null:5>;
val compQuontonium = <MorePlanet:diona_item:2>;
val compFronisium = <MorePlanet:diona_item:3>;
val compPolongius = <MorePlanet:polongnius_item:6>;
val compPalladium = <MorePlanet:polongnius_item:7>;
val compNorium = <MorePlanet:nibiru_item:3>;
val compRedGem = <MorePlanet:nibiru_item:2>;
val comptitanium = <GalacticraftMars:item.itemBasicAsteroids:6>;
val coppercanister = <GalacticraftCore:item.canister:1>;
val t1plate = <GalacticraftCore:item.heavyPlating>;
val t2plate = <GalacticraftMars:item.null:3>;
val t3plate = <GalacticraftMars:item.itemBasicAsteroids:0>;
val t5plate = <MorePlanet:diona_item:4>;
val t6plate = <MorePlanet:tier_6_rocket_module:2>;
val t7plate = <MorePlanet:tier_7_rocket_module:2>;

recipes.remove(gccompressor);
recipes.remove(eleccompressor);
recipes.remove(gcrefinery);
recipes.remove(compcopper);
recipes.remove(comptin);
recipes.remove(compaluminum);
recipes.remove(compsteel);
recipes.remove(compbronze);
recipes.remove(compiron);
recipes.remove(compmeteoriron);
recipes.remove(compdesh);
recipes.remove(comptitanium);
recipes.remove(t1plate);
recipes.remove(t2plate);
recipes.remove(t3plate);

recipes.addShaped(gcrefinery, [[steel, coppercanister, steel], [steel, coppercanister, steel], [compsteel, <ThermalExpansion:Machine:0>, compsteel]]);

mods.mekanism.Compressor.addRecipe(<Railcraft:part.plate:0>*1, compiron*1);
mods.mekanism.Compressor.addRecipe(<Railcraft:part.plate:3>*1, compcopper*1);
mods.mekanism.Compressor.addRecipe(<Railcraft:part.plate:2>*1, comptin*1);
mods.mekanism.Compressor.addRecipe(<Railcraft:part.plate:1>*1, compsteel*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateBronze>*1, compbronze*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateAluminum>*1, compaluminum*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateDesh>*1, compdesh*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateMeteorIron>*1, compmeteoriron*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateTitanium>*1, comptitanium*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateComp>*1, t1plate*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateCompAdv>*1, t2plate*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateCompReinf>*1, t3plate*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateQuontonium>*1, compQuontonium*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateFronisium>*1, compFronisium*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateCompMetal>*1, t5plate*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:platePolongius>*1, compPolongius*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:platePalladium>*1, compPalladium*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateCompMetalAdv>*1, t6plate*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateNorium>*1, compNorium*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateRedGem>*1, compRedGem*1);
mods.mekanism.Compressor.addRecipe(<CustomItems:plateCompMetalReinf>*1, t7plate*1);