val iron = <minecraft:iron_ingot>;
val enrichedalloy = <Mekanism:EnrichedAlloy>;
val servo = <ThermalExpansion:material:0>;
val motor = <ore:motor>;
val leather = <minecraft:leather>;
val mcstring = <minecraft:string>;

val black = <ore:dyeBlack>;
val red = <ore:dyeRed>;
val green= <ore:dyeGreen>;
val brown = <ore:dyeBrown>;
val blue = <ore:dyeBlue>;
val purple = <ore:dyePurple>;
val cyan = <ore:dyeCyan>;
val lightgray = <ore:dyeLightGray>;
val gray = <ore:dyeGray>;
val pink = <ore:dyePink>;
val lime = <ore:dyeLime>;
val yellow = <ore:dyeYellow>;
val lightblue = <ore:dyeLightBlue>;
val magenta = <ore:dyeMagenta>;
val orange = <ore:dyeOrange>;
val white = <ore:dyeWhite>;

val ww2armorbox = <flansmod:armorBox.ww2Armour>;
val germanbox = <flansmod:gunBox.german>;
val britishbox = <flansmod:gunBox.british>;
val americanbox = <flansmod:gunBox.american>;
val japanesebox = <flansmod:gunBox.japanese>;
val sovjetbox = <flansmod:gunBox.russian>;
val modernbox = <flansmod:gunBox.modern>;
val mwarmorbox = <flansmod:armorBox.mwArmour>;
val vehiclebox = <flansmod:flansWorkbench:0>;
val upgradebox = <flansmod:flansWorkbench:1>;

recipes.remove(germanbox);
recipes.remove(britishbox);
recipes.remove(americanbox);
recipes.remove(japanesebox);
recipes.remove(sovjetbox);
recipes.remove(modernbox);
recipes.remove(vehiclebox);
recipes.remove(ww2armorbox);
recipes.remove(mwarmorbox);
recipes.remove(upgradebox);
recipes.addShaped(germanbox, [[iron, enrichedalloy, iron], [red, black, red], [iron, enrichedalloy, iron]]);
recipes.addShaped(britishbox, [[iron, enrichedalloy, iron], [blue, red, blue], [iron, enrichedalloy, iron]]);
recipes.addShaped(americanbox, [[iron, enrichedalloy, iron], [blue, red, red], [iron, enrichedalloy, iron]]);
recipes.addShaped(japanesebox, [[iron, enrichedalloy, iron], [white, red, white], [iron, enrichedalloy, iron]]);
recipes.addShaped(sovjetbox, [[iron, enrichedalloy, iron], [yellow, red, red], [iron, enrichedalloy, iron]]);
recipes.addShaped(modernbox, [[iron, enrichedalloy, iron], [green, green, green], [iron, enrichedalloy, iron]]);
recipes.addShaped(vehiclebox, [[iron, enrichedalloy, iron], [motor, motor, motor], [iron, enrichedalloy, iron]]);
recipes.addShaped(ww2armorbox, [[iron, enrichedalloy, iron], [leather,mcstring,leather],[iron, enrichedalloy, iron]]);
recipes.addShaped(mwarmorbox, [[iron, enrichedalloy, iron], [leather,leather,leather],[iron, enrichedalloy, iron]]);
recipes.addShaped(upgradebox, [[iron, enrichedalloy, iron], [enrichedalloy,servo,enrichedalloy],[iron, enrichedalloy, iron]]);