mods.tconstruct.ToolStats.setHarvestLevel("Ghostwood",0);
mods.tconstruct.ToolStats.setHarvestLevel("Wood",0);
mods.tconstruct.ToolStats.setHarvestLevel("Fusewood",0);
mods.tconstruct.ToolStats.setHarvestLevel("Stone",0);
mods.tconstruct.ToolStats.setHarvestLevel("Refined Glowstone",0);
mods.tconstruct.ToolStats.setHarvestLevel("Iron",1);
mods.tconstruct.ToolStats.setHarvestLevel("Nether Quartz",0);
mods.tconstruct.ToolStats.setHarvestLevel("Flint",0);
mods.tconstruct.ToolStats.setHarvestLevel("Invar",2);
mods.tconstruct.ToolStats.setHarvestLevel("AeonSteel",5);
mods.tconstruct.ToolStats.setHarvestLevel("Pokefennium",5);
mods.tconstruct.ToolStats.setHarvestLevel("Cactus",0);
mods.tconstruct.ToolStats.setHarvestLevel("Nickel",0);
mods.tconstruct.ToolStats.setHarvestLevel("Osmium",3);
mods.tconstruct.ToolStats.setHarvestLevel("Bone",0);
mods.tconstruct.ToolStats.setHarvestLevel("Lead",0);
mods.tconstruct.ToolStats.setHarvestLevel("Dogbearium",5);
mods.tconstruct.ToolStats.setHarvestLevel("Certus Quartz",0);
mods.tconstruct.ToolStats.setHarvestLevel("Obsidian",2);
mods.tconstruct.ToolStats.setHarvestLevel("Silver",1);
mods.tconstruct.ToolStats.setHarvestLevel("Queen's Gold",2);
mods.tconstruct.ToolStats.setHarvestLevel("Fairy",5);
mods.tconstruct.ToolStats.setHarvestLevel("Netherrack",0);
mods.tconstruct.ToolStats.setHarvestLevel("Shiny",4);
mods.tconstruct.ToolStats.setHarvestLevel("Slime",0);
mods.tconstruct.ToolStats.setHarvestLevel("Electrum",2);
mods.tconstruct.ToolStats.setHarvestLevel("Paper",0);
mods.tconstruct.ToolStats.setHarvestLevel("Cobalt",4);
mods.tconstruct.ToolStats.setHarvestLevel("Ardite",4);
mods.tconstruct.ToolStats.setHarvestLevel("Manyullyn",5);
mods.tconstruct.ToolStats.setHarvestLevel("Copper",0);
mods.tconstruct.ToolStats.setHarvestLevel("Darkwood",0);
mods.tconstruct.ToolStats.setHarvestLevel("Bronze",1);
mods.tconstruct.ToolStats.setHarvestLevel("Bloodwood",0);
mods.tconstruct.ToolStats.setHarvestLevel("Alumite",3);
mods.tconstruct.ToolStats.setHarvestLevel("Blue Slime",0);
mods.tconstruct.ToolStats.setHarvestLevel("Steel",2);
mods.tconstruct.ToolStats.setHarvestLevel("Pig Iron",2);
mods.tconstruct.ToolStats.setHarvestLevel("Amethyst",4);
mods.tconstruct.ToolStats.setHarvestLevel("Thaumium",4);